\c devvoltflow;

    GRANT USAGE ON SCHEMA public TO "user_app";

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "user_app";
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "user_app";

    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "user_app";

    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT USAGE, SELECT ON SEQUENCES TO "user_app";
